### ISSUE TITLE
Cannot create Experience Lab (tried Europe West and North)

### ISSUE THREAD

**Issue by joasoze** [microsoft/energy-data-services-experience-lab#11]
I am using the Deploy to Azure button with Arm template. Had three tries that always ends with same error. I am using the SET Subcription that is whitelisted.

****Getting error on dataLoad deployment.**** 
 "code": "InvalidValuesForRequestParameters",
        "message": "Values for request parameters are invalid: signedExpiry."

See also attached image. 
![dataload](https://user-images.githubusercontent.com/66827383/205290957-a6d72ff4-3ff7-469c-9352-fa39d68a5a88.png)

Jon Olav Abeland
jabeland@microsoft.com

**Comment by danieljamescarpenter** [comment]
Thanks for submitting this. I've found the issue and should have a fix completed soon.
