### ISSUE TITLE
Customer is getting unauthorized access when trying to access the app service.

### ISSUE THREAD

**Issue by Aditi-Nagarkar** [microsoft/energy-data-services-experience-lab#15]
![image](https://user-images.githubusercontent.com/106385967/208826953-af8571c1-58c4-409c-9c00-26c82b4e3b7d.png)

![image](https://user-images.githubusercontent.com/106385967/208826907-ab8ef067-43f6-4f49-be72-fa29969fef80.png)

![image](https://user-images.githubusercontent.com/106385967/208826644-9e446441-0db5-49b7-9907-311faf3fecab.png)

![image](https://user-images.githubusercontent.com/106385967/208826717-8c613fc4-c416-48a2-abdf-53be81838262.png)

**Comment by Kyle-MSFT** [comment]
Using AAD groups for authorization is not a tested scenario - I'm not even sure it's supported by MEDS. I recommend assigning individual users instead.

**Comment by anu02mpt** [comment]
As mentioned above "I recommend assigning individual users instead", do you mean that each user should deploy individual experience lab instance by giving input their individual 'object id' in 'Default User Id' as shown in the screenshot and then each user can able to access the experience lab instance.

![screenshot](https://user-images.githubusercontent.com/50790337/209535910-2f0a9097-3dd8-4c40-86db-dbdce524c27e.JPG)

**Comment by Kyle-MSFT** [comment]
The default user would go to the website portal and add users under the "user management" page, using their object ids.
